name: Bad CI Pipeline

on: [push]

jobs:
  everything_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run everything at once
        run: |
          pip install pytest
          pytest tests/test_main.py
          
          echo "Деплой на сервер 192.168.1.1..."
          echo "Пароль: im_tired_of_physics!"
          echo "Приложение успешно задеплоено"