name: Bad CI Pipeline

on: [push]

jobs:
  everything_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Setup
        run: |
          curl -sSL http://example.com/setup-server.sh | sudo bash
        
          pip install -r requirements.txt
          pytest tests/test_main.py