name: Bad CI Pipeline

on: [push]

jobs:
  everything_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Setup
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          
          docker --version
        
          pip install -r program_for_lab3/requirements.txt
          python -m pytest program_for_lab3/tests/test_main.py
